import = ["/Users/mfpr/.config/alacritty/themes/themes/github_dark_high_contrast.toml"]


[colors]
draw_bold_text_with_bright_colors = false

[env]
SHELL = "/opt/homebrew/bin/fish" 

[font]
size = 14

[font.offset]
x = 1
y = 4 

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[font.bold]
family = "UbuntuMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "UbuntuMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "UbuntuMono Nerd Font"
style = "Italic"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[window]
decorations = "Full" 
opacity = 1

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 0 
y = 0 

[cursor]
style = { shape = "Underline", blinking = "On" }
